finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_10_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_10_plate_2.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_11_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_14_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_16_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_17_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_18_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_20_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_21_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_22_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_25_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_25_plate_2.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_30_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_32_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_33_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_35_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_3_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_3_plate_2.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_40_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_41_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_42_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_43_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_44_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_45_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_46_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_4_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_51_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_52_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_53_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_54_plate_1.JPG" scoopy_i_
finding_hog_features.exe ".\data_set_phase1_5_11_2560\scoopy_i\scoopy_i_roi\scoopyi_5_plate_2.JPG" scoopy_i_
